### ISSUE TITLE
readconfig and storeconfig request for MAXIMIZE

### ISSUE THREAD

**Issue by dubeckym** [QWalk/mainline#13]
i would like to ask developers to add these features
use of MAXIMIZE would benefit from readconfig and storeconfig

**Comment by lkwagner** [comment]
Hi Matus,

What do you want to do with readconfig/storeconfig? I'm not sure what the use case is for that.

**Comment by dubeckym** [comment]
Dear Lucas,
thank you for asking,
readconfig - will profit from the possibility to read reproducible walker set - e.g. for comparison of maxima of different trial wavefunctions
storeconfig - for postprocessing (analysis/visualization as e.g. shown in Luchow paper)  but also for iterative use with readconfig as described above
maybe more ideas will come along...
Best wishes,
Matus

---

On Mon, 11/30/15, lkwagner notifications@github.com wrote:

 Subject: Re: [mainline] readconfig and storeconfig request for MAXIMIZE (#13)
 To: "QWalk/mainline" mainline@noreply.github.com
 Cc: "dubeckym" matusdubecky@yahoo.com
 Date: Monday, November 30, 2015, 3:36 PM

 Hi Matus,

 What do you want to do with readconfig/storeconfig?
 I'm not sure what the use case is for that.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by lkwagner** [comment]
Maximize has been extended with a bunch of this functionality.
