### ISSUE TITLE
Autogen: Adding a job_record['control'] parameter will clash with currently existing Autogen job directories.

### ISSUE THREAD

**Issue by bbusemeyer** [QWalk/mainline#6]
For example, I just added job_record['control']['force_retry'], and that causes a key error for my currently run jobs. A workaround is to comment out

`record['control']=record_read['control']`

in job_control.execute() for one pass through. This allows it to update the control part of the record json in the directories. 

Maybe we should just copy over existing keys from the JSON job_record as a solution?

**Comment by lkwagner** [comment]
If you comment out that line, then it will not be able to know the queue ID numbers, which would break the system. 

In my experience, this retry functionality ended up being more trouble than it was worth. The script would keep resubmitting runs that had no chance of converging, wasting time. Didn't we agree that we would just give up after 200 iterations?

**Comment by bbusemeyer** [comment]
I added the "force_retry" to allow that option if we did want it, but it's disallowed by default. I fine with just dropping that option entirely, but next time we want to add any control option that may be more important, it won't be added to any existing JSON records.

**Comment by lkwagner** [comment]
Well, that's telling us something about the design. I think it's useful to have a persistent section of the job_record, which allows us to carry control information. 
If 'force_retry' does not fit into that persistent section, then it shouldn't be there at all. To me, 'retry' should be specific to a given run. If it's in control, what does it apply to? Why would we want a blanket 'retry' statement? They mean very different things in QMC and DFT.

**Comment by bbusemeyer** [comment]
Right, retry probably belongs more in the 'dft' section. I do agree that 'control' should be static when using the functioning code, but in terms of code development, it will be difficult to change the makeup of 'control' if we wanted to add a new feature.

**Comment by lkwagner** [comment]
OK, so regarding your pull request:
We should keep:
- restart_from
- checking of autogen.d12 in cif2crystal
- properties submission option (check that both work!)

We should remove:
- ['control']['force_retry']: this is not a decision that execute() is supposed to be making
- Crystal has failed if it doesn't converge in 200 cycles, in my opinion.
- retries of crystal. For the moment, let's just let it die.
- .gitignore shouldn't have taub.mk in it. Just suck it up.

I'm still unsure about ['control']['incomplete']. I would recommend removing it until we actually need it for something. Right now it seems to be baggage which doesn't do anything. It's easy enough to add it if we need it, and it could be needed in a slightly different form anyway.

**Comment by bbusemeyer** [comment]
Per our discussion, the user should keep the same version of autogen or else fix it manually.
