### ISSUE TITLE
Autogen: Need for documentation structure for job_record options.

### ISSUE THREAD

**Issue by bbusemeyer** [QWalk/mainline#8]
From Lucas's comment:
1. A data structure that follows the job_record data structure, but elements are dictionaries containing:
   'default' : default value
   'documentation':string containing documentation of the option
   This is then the documentation for the allowed elements and also the defaults in one place.
2. A function which takes the documentation data structure and a proposed job_record. If there are keys in the proposed job_record which are not in the documentation data structure, then raise an error.
3. the default function can now just run through the data structure and generate a default record, instead of having the defaults hard-coded.

**Comment by lkwagner** [comment]
1. has been done by the use of a JSON schema. That's available in the autogen/ subdirectory.
